import { LatLng, LatLngBounds } from "../entities/LatLng";
import { MapController } from "./MapController";
import { IBoundGridContentData, IBoundGridData, IMarkerData } from "../entities/Response";
import { IMarkerList } from "./IMarkers";
import { IController } from "./IController";
export declare class YahooMapController extends MapController<Y.Marker> {
    private map;
    private yc;
    private parentCentre?;
    private readonly _grid;
    private readonly _msg;
    private readonly _loading;
    constructor(root: IController);
    protected init(): void;
    getBounds(): LatLngBounds | null;
    getZoom(): number;
    setZoom(number: number): void;
    getCenter(): LatLng;
    setCenter(coordinate: LatLng): void;
    addMarker(marker: IMarkerData): IMarkerData;
    removeMarker(id: string): boolean;
    setUI(show: boolean): void;
    protected openModal(marker: IMarkerList<Y.Marker>): void;
    addGrids(grids: IBoundGridData[]): void;
    addGridContents(contents: IBoundGridContentData[]): void;
    removeGrids(): void;
    setMessage(message: string, show: boolean): void;
    showMessage(): void;
    hideMessage(): void;
    showLoading(): void;
    hideLoading(): void;
}
