name: publish
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        node-version: [18.x]
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ueno-bst'
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Generate Codes 
        run: npm run build
      - name: Commit and Push Generated code to release Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "t-ueno@bstinc.co.jp"
          git checkout -b release
          git add --all
          git commit -m "Generated code by Github Actions" || exit 0
          git push -u origin release
      - name: Publish GitHub Package
        run: npm publish
