name: publish
on:
  workflow_dispatch:
  push:
    tags: 
      - 'v*'
jobs:
  convert:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Npm Publish
        uses: actions/setup-node@v2.5.2
        with:
          node_version: '19.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ueno-bst'
          cache: npm
      - run: npm ci
      - run: npm run release
      - run: npm publish
        env:
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
        
